// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

#include "Protocol.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Protocol {

inline constexpr SIGNUP_REQ::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : userid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        email_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SIGNUP_REQ::SIGNUP_REQ(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SIGNUP_REQDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SIGNUP_REQDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SIGNUP_REQDefaultTypeInternal() {}
  union {
    SIGNUP_REQ _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SIGNUP_REQDefaultTypeInternal _SIGNUP_REQ_default_instance_;

inline constexpr SIGNUP_ACK::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SIGNUP_ACK::SIGNUP_ACK(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SIGNUP_ACKDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SIGNUP_ACKDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SIGNUP_ACKDefaultTypeInternal() {}
  union {
    SIGNUP_ACK _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SIGNUP_ACKDefaultTypeInternal _SIGNUP_ACK_default_instance_;

inline constexpr LOGIN_REQ::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : userid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LOGIN_REQ::LOGIN_REQ(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LOGIN_REQDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LOGIN_REQDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LOGIN_REQDefaultTypeInternal() {}
  union {
    LOGIN_REQ _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LOGIN_REQDefaultTypeInternal _LOGIN_REQ_default_instance_;

inline constexpr ENTER_GAME_REQ::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : playerindex_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ENTER_GAME_REQ::ENTER_GAME_REQ(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ENTER_GAME_REQDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ENTER_GAME_REQDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ENTER_GAME_REQDefaultTypeInternal() {}
  union {
    ENTER_GAME_REQ _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ENTER_GAME_REQDefaultTypeInternal _ENTER_GAME_REQ_default_instance_;

inline constexpr ENTER_GAME_ACK::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ENTER_GAME_ACK::ENTER_GAME_ACK(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ENTER_GAME_ACKDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ENTER_GAME_ACKDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ENTER_GAME_ACKDefaultTypeInternal() {}
  union {
    ENTER_GAME_ACK _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ENTER_GAME_ACKDefaultTypeInternal _ENTER_GAME_ACK_default_instance_;

inline constexpr CREATE_CHARACTER_REQ::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : charactername_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CREATE_CHARACTER_REQ::CREATE_CHARACTER_REQ(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CREATE_CHARACTER_REQDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CREATE_CHARACTER_REQDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CREATE_CHARACTER_REQDefaultTypeInternal() {}
  union {
    CREATE_CHARACTER_REQ _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CREATE_CHARACTER_REQDefaultTypeInternal _CREATE_CHARACTER_REQ_default_instance_;

inline constexpr CREATE_CHARACTER_ACK::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CREATE_CHARACTER_ACK::CREATE_CHARACTER_ACK(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CREATE_CHARACTER_ACKDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CREATE_CHARACTER_ACKDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CREATE_CHARACTER_ACKDefaultTypeInternal() {}
  union {
    CREATE_CHARACTER_ACK _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CREATE_CHARACTER_ACKDefaultTypeInternal _CREATE_CHARACTER_ACK_default_instance_;

inline constexpr CHAT_REQ::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CHAT_REQ::CHAT_REQ(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CHAT_REQDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CHAT_REQDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CHAT_REQDefaultTypeInternal() {}
  union {
    CHAT_REQ _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CHAT_REQDefaultTypeInternal _CHAT_REQ_default_instance_;

inline constexpr CHAT_ACK::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        playerid_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CHAT_ACK::CHAT_ACK(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CHAT_ACKDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CHAT_ACKDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CHAT_ACKDefaultTypeInternal() {}
  union {
    CHAT_ACK _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CHAT_ACKDefaultTypeInternal _CHAT_ACK_default_instance_;

inline constexpr LOGIN_ACK::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : players_{},
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LOGIN_ACK::LOGIN_ACK(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LOGIN_ACKDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LOGIN_ACKDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LOGIN_ACKDefaultTypeInternal() {}
  union {
    LOGIN_ACK _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LOGIN_ACKDefaultTypeInternal _LOGIN_ACK_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_Protocol_2eproto[10];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Protocol_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Protocol_2eproto = nullptr;
const ::uint32_t TableStruct_Protocol_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Protocol::SIGNUP_REQ, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Protocol::SIGNUP_REQ, _impl_.userid_),
    PROTOBUF_FIELD_OFFSET(::Protocol::SIGNUP_REQ, _impl_.password_),
    PROTOBUF_FIELD_OFFSET(::Protocol::SIGNUP_REQ, _impl_.email_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Protocol::SIGNUP_ACK, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Protocol::SIGNUP_ACK, _impl_.success_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Protocol::CREATE_CHARACTER_REQ, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Protocol::CREATE_CHARACTER_REQ, _impl_.charactername_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Protocol::CREATE_CHARACTER_ACK, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Protocol::CREATE_CHARACTER_ACK, _impl_.success_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Protocol::LOGIN_REQ, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Protocol::LOGIN_REQ, _impl_.userid_),
    PROTOBUF_FIELD_OFFSET(::Protocol::LOGIN_REQ, _impl_.password_),
    PROTOBUF_FIELD_OFFSET(::Protocol::LOGIN_REQ, _impl_.token_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Protocol::LOGIN_ACK, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Protocol::LOGIN_ACK, _impl_.success_),
    PROTOBUF_FIELD_OFFSET(::Protocol::LOGIN_ACK, _impl_.players_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Protocol::ENTER_GAME_REQ, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Protocol::ENTER_GAME_REQ, _impl_.playerindex_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Protocol::ENTER_GAME_ACK, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Protocol::ENTER_GAME_ACK, _impl_.success_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Protocol::CHAT_REQ, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Protocol::CHAT_REQ, _impl_.msg_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Protocol::CHAT_ACK, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Protocol::CHAT_ACK, _impl_.playerid_),
    PROTOBUF_FIELD_OFFSET(::Protocol::CHAT_ACK, _impl_.msg_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Protocol::SIGNUP_REQ)},
        {11, -1, -1, sizeof(::Protocol::SIGNUP_ACK)},
        {20, -1, -1, sizeof(::Protocol::CREATE_CHARACTER_REQ)},
        {29, -1, -1, sizeof(::Protocol::CREATE_CHARACTER_ACK)},
        {38, -1, -1, sizeof(::Protocol::LOGIN_REQ)},
        {49, -1, -1, sizeof(::Protocol::LOGIN_ACK)},
        {59, -1, -1, sizeof(::Protocol::ENTER_GAME_REQ)},
        {68, -1, -1, sizeof(::Protocol::ENTER_GAME_ACK)},
        {77, -1, -1, sizeof(::Protocol::CHAT_REQ)},
        {86, -1, -1, sizeof(::Protocol::CHAT_ACK)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::Protocol::_SIGNUP_REQ_default_instance_._instance,
    &::Protocol::_SIGNUP_ACK_default_instance_._instance,
    &::Protocol::_CREATE_CHARACTER_REQ_default_instance_._instance,
    &::Protocol::_CREATE_CHARACTER_ACK_default_instance_._instance,
    &::Protocol::_LOGIN_REQ_default_instance_._instance,
    &::Protocol::_LOGIN_ACK_default_instance_._instance,
    &::Protocol::_ENTER_GAME_REQ_default_instance_._instance,
    &::Protocol::_ENTER_GAME_ACK_default_instance_._instance,
    &::Protocol::_CHAT_REQ_default_instance_._instance,
    &::Protocol::_CHAT_ACK_default_instance_._instance,
};
const char descriptor_table_protodef_Protocol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\016Protocol.proto\022\010Protocol\032\014Struct.proto"
    "\"=\n\nSIGNUP_REQ\022\016\n\006userId\030\001 \001(\t\022\020\n\010passwo"
    "rd\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\"\035\n\nSIGNUP_ACK\022\017\n"
    "\007success\030\001 \001(\010\"-\n\024CREATE_CHARACTER_REQ\022\025"
    "\n\rcharacterName\030\001 \001(\t\"\'\n\024CREATE_CHARACTE"
    "R_ACK\022\017\n\007success\030\001 \001(\010\"<\n\tLOGIN_REQ\022\016\n\006u"
    "serId\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\022\r\n\005token\030\003"
    " \001(\t\"C\n\tLOGIN_ACK\022\017\n\007success\030\001 \001(\010\022%\n\007pl"
    "ayers\030\002 \003(\0132\024.Protocol.PlayerInfo\"%\n\016ENT"
    "ER_GAME_REQ\022\023\n\013playerIndex\030\001 \001(\004\"!\n\016ENTE"
    "R_GAME_ACK\022\017\n\007success\030\001 \001(\010\"\027\n\010CHAT_REQ\022"
    "\013\n\003msg\030\001 \001(\t\")\n\010CHAT_ACK\022\020\n\010playerId\030\001 \001"
    "(\004\022\013\n\003msg\030\002 \001(\tb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_Protocol_2eproto_deps[1] =
    {
        &::descriptor_table_Struct_2eproto,
};
static ::absl::once_flag descriptor_table_Protocol_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Protocol_2eproto = {
    false,
    false,
    503,
    descriptor_table_protodef_Protocol_2eproto,
    "Protocol.proto",
    &descriptor_table_Protocol_2eproto_once,
    descriptor_table_Protocol_2eproto_deps,
    1,
    10,
    schemas,
    file_default_instances,
    TableStruct_Protocol_2eproto::offsets,
    file_level_metadata_Protocol_2eproto,
    file_level_enum_descriptors_Protocol_2eproto,
    file_level_service_descriptors_Protocol_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Protocol_2eproto_getter() {
  return &descriptor_table_Protocol_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Protocol_2eproto(&descriptor_table_Protocol_2eproto);
namespace Protocol {
// ===================================================================

class SIGNUP_REQ::_Internal {
 public:
};

SIGNUP_REQ::SIGNUP_REQ(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.SIGNUP_REQ)
}
inline PROTOBUF_NDEBUG_INLINE SIGNUP_REQ::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : userid_(arena, from.userid_),
        password_(arena, from.password_),
        email_(arena, from.email_),
        _cached_size_{0} {}

SIGNUP_REQ::SIGNUP_REQ(
    ::google::protobuf::Arena* arena,
    const SIGNUP_REQ& from)
    : ::google::protobuf::Message(arena) {
  SIGNUP_REQ* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:Protocol.SIGNUP_REQ)
}
inline PROTOBUF_NDEBUG_INLINE SIGNUP_REQ::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : userid_(arena),
        password_(arena),
        email_(arena),
        _cached_size_{0} {}

inline void SIGNUP_REQ::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SIGNUP_REQ::~SIGNUP_REQ() {
  // @@protoc_insertion_point(destructor:Protocol.SIGNUP_REQ)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SIGNUP_REQ::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.userid_.Destroy();
  _impl_.password_.Destroy();
  _impl_.email_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void SIGNUP_REQ::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.SIGNUP_REQ)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.userid_.ClearToEmpty();
  _impl_.password_.ClearToEmpty();
  _impl_.email_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* SIGNUP_REQ::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 47, 2> SIGNUP_REQ::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_SIGNUP_REQ_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string userId = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SIGNUP_REQ, _impl_.userid_)}},
    // string password = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(SIGNUP_REQ, _impl_.password_)}},
    // string email = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(SIGNUP_REQ, _impl_.email_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string userId = 1;
    {PROTOBUF_FIELD_OFFSET(SIGNUP_REQ, _impl_.userid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string password = 2;
    {PROTOBUF_FIELD_OFFSET(SIGNUP_REQ, _impl_.password_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string email = 3;
    {PROTOBUF_FIELD_OFFSET(SIGNUP_REQ, _impl_.email_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\6\10\5\0\0\0\0"
    "Protocol.SIGNUP_REQ"
    "userId"
    "password"
    "email"
  }},
};

::uint8_t* SIGNUP_REQ::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.SIGNUP_REQ)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string userId = 1;
  if (!this->_internal_userid().empty()) {
    const std::string& _s = this->_internal_userid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.SIGNUP_REQ.userId");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string password = 2;
  if (!this->_internal_password().empty()) {
    const std::string& _s = this->_internal_password();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.SIGNUP_REQ.password");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string email = 3;
  if (!this->_internal_email().empty()) {
    const std::string& _s = this->_internal_email();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.SIGNUP_REQ.email");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.SIGNUP_REQ)
  return target;
}

::size_t SIGNUP_REQ::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.SIGNUP_REQ)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string userId = 1;
  if (!this->_internal_userid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_userid());
  }

  // string password = 2;
  if (!this->_internal_password().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_password());
  }

  // string email = 3;
  if (!this->_internal_email().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_email());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData SIGNUP_REQ::_class_data_ = {
    SIGNUP_REQ::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* SIGNUP_REQ::GetClassData() const {
  return &_class_data_;
}

void SIGNUP_REQ::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<SIGNUP_REQ*>(&to_msg);
  auto& from = static_cast<const SIGNUP_REQ&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.SIGNUP_REQ)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_userid().empty()) {
    _this->_internal_set_userid(from._internal_userid());
  }
  if (!from._internal_password().empty()) {
    _this->_internal_set_password(from._internal_password());
  }
  if (!from._internal_email().empty()) {
    _this->_internal_set_email(from._internal_email());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SIGNUP_REQ::CopyFrom(const SIGNUP_REQ& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.SIGNUP_REQ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SIGNUP_REQ::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* SIGNUP_REQ::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void SIGNUP_REQ::InternalSwap(SIGNUP_REQ* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.userid_, &other->_impl_.userid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.password_, &other->_impl_.password_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.email_, &other->_impl_.email_, arena);
}

::google::protobuf::Metadata SIGNUP_REQ::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[0]);
}
// ===================================================================

class SIGNUP_ACK::_Internal {
 public:
};

SIGNUP_ACK::SIGNUP_ACK(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.SIGNUP_ACK)
}
SIGNUP_ACK::SIGNUP_ACK(
    ::google::protobuf::Arena* arena, const SIGNUP_ACK& from)
    : SIGNUP_ACK(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE SIGNUP_ACK::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SIGNUP_ACK::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
SIGNUP_ACK::~SIGNUP_ACK() {
  // @@protoc_insertion_point(destructor:Protocol.SIGNUP_ACK)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SIGNUP_ACK::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void SIGNUP_ACK::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.SIGNUP_ACK)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* SIGNUP_ACK::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> SIGNUP_ACK::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_SIGNUP_ACK_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SIGNUP_ACK, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SIGNUP_ACK, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(SIGNUP_ACK, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* SIGNUP_ACK::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.SIGNUP_ACK)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_success(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.SIGNUP_ACK)
  return target;
}

::size_t SIGNUP_ACK::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.SIGNUP_ACK)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData SIGNUP_ACK::_class_data_ = {
    SIGNUP_ACK::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* SIGNUP_ACK::GetClassData() const {
  return &_class_data_;
}

void SIGNUP_ACK::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<SIGNUP_ACK*>(&to_msg);
  auto& from = static_cast<const SIGNUP_ACK&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.SIGNUP_ACK)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SIGNUP_ACK::CopyFrom(const SIGNUP_ACK& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.SIGNUP_ACK)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SIGNUP_ACK::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* SIGNUP_ACK::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void SIGNUP_ACK::InternalSwap(SIGNUP_ACK* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata SIGNUP_ACK::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[1]);
}
// ===================================================================

class CREATE_CHARACTER_REQ::_Internal {
 public:
};

CREATE_CHARACTER_REQ::CREATE_CHARACTER_REQ(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.CREATE_CHARACTER_REQ)
}
inline PROTOBUF_NDEBUG_INLINE CREATE_CHARACTER_REQ::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : charactername_(arena, from.charactername_),
        _cached_size_{0} {}

CREATE_CHARACTER_REQ::CREATE_CHARACTER_REQ(
    ::google::protobuf::Arena* arena,
    const CREATE_CHARACTER_REQ& from)
    : ::google::protobuf::Message(arena) {
  CREATE_CHARACTER_REQ* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:Protocol.CREATE_CHARACTER_REQ)
}
inline PROTOBUF_NDEBUG_INLINE CREATE_CHARACTER_REQ::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : charactername_(arena),
        _cached_size_{0} {}

inline void CREATE_CHARACTER_REQ::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CREATE_CHARACTER_REQ::~CREATE_CHARACTER_REQ() {
  // @@protoc_insertion_point(destructor:Protocol.CREATE_CHARACTER_REQ)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CREATE_CHARACTER_REQ::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.charactername_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CREATE_CHARACTER_REQ::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.CREATE_CHARACTER_REQ)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.charactername_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CREATE_CHARACTER_REQ::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 51, 2> CREATE_CHARACTER_REQ::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CREATE_CHARACTER_REQ_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string characterName = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CREATE_CHARACTER_REQ, _impl_.charactername_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string characterName = 1;
    {PROTOBUF_FIELD_OFFSET(CREATE_CHARACTER_REQ, _impl_.charactername_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\35\15\0\0\0\0\0\0"
    "Protocol.CREATE_CHARACTER_REQ"
    "characterName"
  }},
};

::uint8_t* CREATE_CHARACTER_REQ::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.CREATE_CHARACTER_REQ)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string characterName = 1;
  if (!this->_internal_charactername().empty()) {
    const std::string& _s = this->_internal_charactername();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.CREATE_CHARACTER_REQ.characterName");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.CREATE_CHARACTER_REQ)
  return target;
}

::size_t CREATE_CHARACTER_REQ::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.CREATE_CHARACTER_REQ)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string characterName = 1;
  if (!this->_internal_charactername().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_charactername());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CREATE_CHARACTER_REQ::_class_data_ = {
    CREATE_CHARACTER_REQ::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CREATE_CHARACTER_REQ::GetClassData() const {
  return &_class_data_;
}

void CREATE_CHARACTER_REQ::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CREATE_CHARACTER_REQ*>(&to_msg);
  auto& from = static_cast<const CREATE_CHARACTER_REQ&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.CREATE_CHARACTER_REQ)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_charactername().empty()) {
    _this->_internal_set_charactername(from._internal_charactername());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CREATE_CHARACTER_REQ::CopyFrom(const CREATE_CHARACTER_REQ& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.CREATE_CHARACTER_REQ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CREATE_CHARACTER_REQ::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CREATE_CHARACTER_REQ::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CREATE_CHARACTER_REQ::InternalSwap(CREATE_CHARACTER_REQ* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.charactername_, &other->_impl_.charactername_, arena);
}

::google::protobuf::Metadata CREATE_CHARACTER_REQ::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[2]);
}
// ===================================================================

class CREATE_CHARACTER_ACK::_Internal {
 public:
};

CREATE_CHARACTER_ACK::CREATE_CHARACTER_ACK(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.CREATE_CHARACTER_ACK)
}
CREATE_CHARACTER_ACK::CREATE_CHARACTER_ACK(
    ::google::protobuf::Arena* arena, const CREATE_CHARACTER_ACK& from)
    : CREATE_CHARACTER_ACK(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CREATE_CHARACTER_ACK::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CREATE_CHARACTER_ACK::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
CREATE_CHARACTER_ACK::~CREATE_CHARACTER_ACK() {
  // @@protoc_insertion_point(destructor:Protocol.CREATE_CHARACTER_ACK)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CREATE_CHARACTER_ACK::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CREATE_CHARACTER_ACK::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.CREATE_CHARACTER_ACK)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CREATE_CHARACTER_ACK::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> CREATE_CHARACTER_ACK::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CREATE_CHARACTER_ACK_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CREATE_CHARACTER_ACK, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CREATE_CHARACTER_ACK, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(CREATE_CHARACTER_ACK, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CREATE_CHARACTER_ACK::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.CREATE_CHARACTER_ACK)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_success(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.CREATE_CHARACTER_ACK)
  return target;
}

::size_t CREATE_CHARACTER_ACK::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.CREATE_CHARACTER_ACK)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CREATE_CHARACTER_ACK::_class_data_ = {
    CREATE_CHARACTER_ACK::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CREATE_CHARACTER_ACK::GetClassData() const {
  return &_class_data_;
}

void CREATE_CHARACTER_ACK::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CREATE_CHARACTER_ACK*>(&to_msg);
  auto& from = static_cast<const CREATE_CHARACTER_ACK&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.CREATE_CHARACTER_ACK)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CREATE_CHARACTER_ACK::CopyFrom(const CREATE_CHARACTER_ACK& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.CREATE_CHARACTER_ACK)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CREATE_CHARACTER_ACK::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CREATE_CHARACTER_ACK::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CREATE_CHARACTER_ACK::InternalSwap(CREATE_CHARACTER_ACK* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata CREATE_CHARACTER_ACK::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[3]);
}
// ===================================================================

class LOGIN_REQ::_Internal {
 public:
};

LOGIN_REQ::LOGIN_REQ(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.LOGIN_REQ)
}
inline PROTOBUF_NDEBUG_INLINE LOGIN_REQ::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : userid_(arena, from.userid_),
        password_(arena, from.password_),
        token_(arena, from.token_),
        _cached_size_{0} {}

LOGIN_REQ::LOGIN_REQ(
    ::google::protobuf::Arena* arena,
    const LOGIN_REQ& from)
    : ::google::protobuf::Message(arena) {
  LOGIN_REQ* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:Protocol.LOGIN_REQ)
}
inline PROTOBUF_NDEBUG_INLINE LOGIN_REQ::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : userid_(arena),
        password_(arena),
        token_(arena),
        _cached_size_{0} {}

inline void LOGIN_REQ::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
LOGIN_REQ::~LOGIN_REQ() {
  // @@protoc_insertion_point(destructor:Protocol.LOGIN_REQ)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LOGIN_REQ::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.userid_.Destroy();
  _impl_.password_.Destroy();
  _impl_.token_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void LOGIN_REQ::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.LOGIN_REQ)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.userid_.ClearToEmpty();
  _impl_.password_.ClearToEmpty();
  _impl_.token_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LOGIN_REQ::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 46, 2> LOGIN_REQ::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LOGIN_REQ_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string userId = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(LOGIN_REQ, _impl_.userid_)}},
    // string password = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(LOGIN_REQ, _impl_.password_)}},
    // string token = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(LOGIN_REQ, _impl_.token_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string userId = 1;
    {PROTOBUF_FIELD_OFFSET(LOGIN_REQ, _impl_.userid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string password = 2;
    {PROTOBUF_FIELD_OFFSET(LOGIN_REQ, _impl_.password_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string token = 3;
    {PROTOBUF_FIELD_OFFSET(LOGIN_REQ, _impl_.token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\6\10\5\0\0\0\0"
    "Protocol.LOGIN_REQ"
    "userId"
    "password"
    "token"
  }},
};

::uint8_t* LOGIN_REQ::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.LOGIN_REQ)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string userId = 1;
  if (!this->_internal_userid().empty()) {
    const std::string& _s = this->_internal_userid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.LOGIN_REQ.userId");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string password = 2;
  if (!this->_internal_password().empty()) {
    const std::string& _s = this->_internal_password();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.LOGIN_REQ.password");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string token = 3;
  if (!this->_internal_token().empty()) {
    const std::string& _s = this->_internal_token();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.LOGIN_REQ.token");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.LOGIN_REQ)
  return target;
}

::size_t LOGIN_REQ::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.LOGIN_REQ)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string userId = 1;
  if (!this->_internal_userid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_userid());
  }

  // string password = 2;
  if (!this->_internal_password().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_password());
  }

  // string token = 3;
  if (!this->_internal_token().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_token());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData LOGIN_REQ::_class_data_ = {
    LOGIN_REQ::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* LOGIN_REQ::GetClassData() const {
  return &_class_data_;
}

void LOGIN_REQ::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<LOGIN_REQ*>(&to_msg);
  auto& from = static_cast<const LOGIN_REQ&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.LOGIN_REQ)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_userid().empty()) {
    _this->_internal_set_userid(from._internal_userid());
  }
  if (!from._internal_password().empty()) {
    _this->_internal_set_password(from._internal_password());
  }
  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LOGIN_REQ::CopyFrom(const LOGIN_REQ& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.LOGIN_REQ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LOGIN_REQ::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* LOGIN_REQ::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void LOGIN_REQ::InternalSwap(LOGIN_REQ* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.userid_, &other->_impl_.userid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.password_, &other->_impl_.password_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
}

::google::protobuf::Metadata LOGIN_REQ::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[4]);
}
// ===================================================================

class LOGIN_ACK::_Internal {
 public:
};

void LOGIN_ACK::clear_players() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.players_.Clear();
}
LOGIN_ACK::LOGIN_ACK(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.LOGIN_ACK)
}
inline PROTOBUF_NDEBUG_INLINE LOGIN_ACK::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : players_{visibility, arena, from.players_},
        _cached_size_{0} {}

LOGIN_ACK::LOGIN_ACK(
    ::google::protobuf::Arena* arena,
    const LOGIN_ACK& from)
    : ::google::protobuf::Message(arena) {
  LOGIN_ACK* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.success_ = from._impl_.success_;

  // @@protoc_insertion_point(copy_constructor:Protocol.LOGIN_ACK)
}
inline PROTOBUF_NDEBUG_INLINE LOGIN_ACK::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : players_{visibility, arena},
        _cached_size_{0} {}

inline void LOGIN_ACK::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
LOGIN_ACK::~LOGIN_ACK() {
  // @@protoc_insertion_point(destructor:Protocol.LOGIN_ACK)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LOGIN_ACK::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void LOGIN_ACK::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.LOGIN_ACK)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.players_.Clear();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LOGIN_ACK::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> LOGIN_ACK::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_LOGIN_ACK_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .Protocol.PlayerInfo players = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(LOGIN_ACK, _impl_.players_)}},
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(LOGIN_ACK, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(LOGIN_ACK, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(LOGIN_ACK, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // repeated .Protocol.PlayerInfo players = 2;
    {PROTOBUF_FIELD_OFFSET(LOGIN_ACK, _impl_.players_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Protocol::PlayerInfo>()},
  }}, {{
  }},
};

::uint8_t* LOGIN_ACK::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.LOGIN_ACK)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_success(), target);
  }

  // repeated .Protocol.PlayerInfo players = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_players_size()); i < n; i++) {
    const auto& repfield = this->_internal_players().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.LOGIN_ACK)
  return target;
}

::size_t LOGIN_ACK::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.LOGIN_ACK)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Protocol.PlayerInfo players = 2;
  total_size += 1UL * this->_internal_players_size();
  for (const auto& msg : this->_internal_players()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData LOGIN_ACK::_class_data_ = {
    LOGIN_ACK::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* LOGIN_ACK::GetClassData() const {
  return &_class_data_;
}

void LOGIN_ACK::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<LOGIN_ACK*>(&to_msg);
  auto& from = static_cast<const LOGIN_ACK&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.LOGIN_ACK)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_players()->MergeFrom(
      from._internal_players());
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LOGIN_ACK::CopyFrom(const LOGIN_ACK& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.LOGIN_ACK)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LOGIN_ACK::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* LOGIN_ACK::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void LOGIN_ACK::InternalSwap(LOGIN_ACK* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.players_.InternalSwap(&other->_impl_.players_);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata LOGIN_ACK::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[5]);
}
// ===================================================================

class ENTER_GAME_REQ::_Internal {
 public:
};

ENTER_GAME_REQ::ENTER_GAME_REQ(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.ENTER_GAME_REQ)
}
ENTER_GAME_REQ::ENTER_GAME_REQ(
    ::google::protobuf::Arena* arena, const ENTER_GAME_REQ& from)
    : ENTER_GAME_REQ(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ENTER_GAME_REQ::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ENTER_GAME_REQ::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.playerindex_ = {};
}
ENTER_GAME_REQ::~ENTER_GAME_REQ() {
  // @@protoc_insertion_point(destructor:Protocol.ENTER_GAME_REQ)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ENTER_GAME_REQ::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ENTER_GAME_REQ::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.ENTER_GAME_REQ)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.playerindex_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ENTER_GAME_REQ::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ENTER_GAME_REQ::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ENTER_GAME_REQ_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // uint64 playerIndex = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ENTER_GAME_REQ, _impl_.playerindex_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ENTER_GAME_REQ, _impl_.playerindex_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 playerIndex = 1;
    {PROTOBUF_FIELD_OFFSET(ENTER_GAME_REQ, _impl_.playerindex_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* ENTER_GAME_REQ::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.ENTER_GAME_REQ)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 playerIndex = 1;
  if (this->_internal_playerindex() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_playerindex(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.ENTER_GAME_REQ)
  return target;
}

::size_t ENTER_GAME_REQ::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.ENTER_GAME_REQ)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 playerIndex = 1;
  if (this->_internal_playerindex() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_playerindex());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ENTER_GAME_REQ::_class_data_ = {
    ENTER_GAME_REQ::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ENTER_GAME_REQ::GetClassData() const {
  return &_class_data_;
}

void ENTER_GAME_REQ::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ENTER_GAME_REQ*>(&to_msg);
  auto& from = static_cast<const ENTER_GAME_REQ&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.ENTER_GAME_REQ)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_playerindex() != 0) {
    _this->_internal_set_playerindex(from._internal_playerindex());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ENTER_GAME_REQ::CopyFrom(const ENTER_GAME_REQ& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.ENTER_GAME_REQ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ENTER_GAME_REQ::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ENTER_GAME_REQ::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ENTER_GAME_REQ::InternalSwap(ENTER_GAME_REQ* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.playerindex_, other->_impl_.playerindex_);
}

::google::protobuf::Metadata ENTER_GAME_REQ::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[6]);
}
// ===================================================================

class ENTER_GAME_ACK::_Internal {
 public:
};

ENTER_GAME_ACK::ENTER_GAME_ACK(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.ENTER_GAME_ACK)
}
ENTER_GAME_ACK::ENTER_GAME_ACK(
    ::google::protobuf::Arena* arena, const ENTER_GAME_ACK& from)
    : ENTER_GAME_ACK(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ENTER_GAME_ACK::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ENTER_GAME_ACK::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
ENTER_GAME_ACK::~ENTER_GAME_ACK() {
  // @@protoc_insertion_point(destructor:Protocol.ENTER_GAME_ACK)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ENTER_GAME_ACK::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ENTER_GAME_ACK::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.ENTER_GAME_ACK)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ENTER_GAME_ACK::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ENTER_GAME_ACK::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ENTER_GAME_ACK_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ENTER_GAME_ACK, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ENTER_GAME_ACK, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(ENTER_GAME_ACK, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* ENTER_GAME_ACK::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.ENTER_GAME_ACK)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_success(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.ENTER_GAME_ACK)
  return target;
}

::size_t ENTER_GAME_ACK::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.ENTER_GAME_ACK)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ENTER_GAME_ACK::_class_data_ = {
    ENTER_GAME_ACK::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ENTER_GAME_ACK::GetClassData() const {
  return &_class_data_;
}

void ENTER_GAME_ACK::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ENTER_GAME_ACK*>(&to_msg);
  auto& from = static_cast<const ENTER_GAME_ACK&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.ENTER_GAME_ACK)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ENTER_GAME_ACK::CopyFrom(const ENTER_GAME_ACK& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.ENTER_GAME_ACK)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ENTER_GAME_ACK::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ENTER_GAME_ACK::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ENTER_GAME_ACK::InternalSwap(ENTER_GAME_ACK* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata ENTER_GAME_ACK::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[7]);
}
// ===================================================================

class CHAT_REQ::_Internal {
 public:
};

CHAT_REQ::CHAT_REQ(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.CHAT_REQ)
}
inline PROTOBUF_NDEBUG_INLINE CHAT_REQ::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : msg_(arena, from.msg_),
        _cached_size_{0} {}

CHAT_REQ::CHAT_REQ(
    ::google::protobuf::Arena* arena,
    const CHAT_REQ& from)
    : ::google::protobuf::Message(arena) {
  CHAT_REQ* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:Protocol.CHAT_REQ)
}
inline PROTOBUF_NDEBUG_INLINE CHAT_REQ::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : msg_(arena),
        _cached_size_{0} {}

inline void CHAT_REQ::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CHAT_REQ::~CHAT_REQ() {
  // @@protoc_insertion_point(destructor:Protocol.CHAT_REQ)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CHAT_REQ::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.msg_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CHAT_REQ::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.CHAT_REQ)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msg_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CHAT_REQ::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 29, 2> CHAT_REQ::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CHAT_REQ_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string msg = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CHAT_REQ, _impl_.msg_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string msg = 1;
    {PROTOBUF_FIELD_OFFSET(CHAT_REQ, _impl_.msg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\3\0\0\0\0\0\0"
    "Protocol.CHAT_REQ"
    "msg"
  }},
};

::uint8_t* CHAT_REQ::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.CHAT_REQ)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string msg = 1;
  if (!this->_internal_msg().empty()) {
    const std::string& _s = this->_internal_msg();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.CHAT_REQ.msg");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.CHAT_REQ)
  return target;
}

::size_t CHAT_REQ::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.CHAT_REQ)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string msg = 1;
  if (!this->_internal_msg().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_msg());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CHAT_REQ::_class_data_ = {
    CHAT_REQ::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CHAT_REQ::GetClassData() const {
  return &_class_data_;
}

void CHAT_REQ::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CHAT_REQ*>(&to_msg);
  auto& from = static_cast<const CHAT_REQ&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.CHAT_REQ)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_msg().empty()) {
    _this->_internal_set_msg(from._internal_msg());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CHAT_REQ::CopyFrom(const CHAT_REQ& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.CHAT_REQ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CHAT_REQ::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CHAT_REQ::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CHAT_REQ::InternalSwap(CHAT_REQ* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, &other->_impl_.msg_, arena);
}

::google::protobuf::Metadata CHAT_REQ::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[8]);
}
// ===================================================================

class CHAT_ACK::_Internal {
 public:
};

CHAT_ACK::CHAT_ACK(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.CHAT_ACK)
}
inline PROTOBUF_NDEBUG_INLINE CHAT_ACK::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : msg_(arena, from.msg_),
        _cached_size_{0} {}

CHAT_ACK::CHAT_ACK(
    ::google::protobuf::Arena* arena,
    const CHAT_ACK& from)
    : ::google::protobuf::Message(arena) {
  CHAT_ACK* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.playerid_ = from._impl_.playerid_;

  // @@protoc_insertion_point(copy_constructor:Protocol.CHAT_ACK)
}
inline PROTOBUF_NDEBUG_INLINE CHAT_ACK::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : msg_(arena),
        _cached_size_{0} {}

inline void CHAT_ACK::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.playerid_ = {};
}
CHAT_ACK::~CHAT_ACK() {
  // @@protoc_insertion_point(destructor:Protocol.CHAT_ACK)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CHAT_ACK::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.msg_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CHAT_ACK::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.CHAT_ACK)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msg_.ClearToEmpty();
  _impl_.playerid_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CHAT_ACK::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 29, 2> CHAT_ACK::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CHAT_ACK_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string msg = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CHAT_ACK, _impl_.msg_)}},
    // uint64 playerId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CHAT_ACK, _impl_.playerid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CHAT_ACK, _impl_.playerid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 playerId = 1;
    {PROTOBUF_FIELD_OFFSET(CHAT_ACK, _impl_.playerid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // string msg = 2;
    {PROTOBUF_FIELD_OFFSET(CHAT_ACK, _impl_.msg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\0\3\0\0\0\0\0"
    "Protocol.CHAT_ACK"
    "msg"
  }},
};

::uint8_t* CHAT_ACK::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.CHAT_ACK)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 playerId = 1;
  if (this->_internal_playerid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_playerid(), target);
  }

  // string msg = 2;
  if (!this->_internal_msg().empty()) {
    const std::string& _s = this->_internal_msg();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.CHAT_ACK.msg");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.CHAT_ACK)
  return target;
}

::size_t CHAT_ACK::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.CHAT_ACK)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string msg = 2;
  if (!this->_internal_msg().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_msg());
  }

  // uint64 playerId = 1;
  if (this->_internal_playerid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_playerid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CHAT_ACK::_class_data_ = {
    CHAT_ACK::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CHAT_ACK::GetClassData() const {
  return &_class_data_;
}

void CHAT_ACK::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CHAT_ACK*>(&to_msg);
  auto& from = static_cast<const CHAT_ACK&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.CHAT_ACK)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_msg().empty()) {
    _this->_internal_set_msg(from._internal_msg());
  }
  if (from._internal_playerid() != 0) {
    _this->_internal_set_playerid(from._internal_playerid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CHAT_ACK::CopyFrom(const CHAT_ACK& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.CHAT_ACK)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CHAT_ACK::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CHAT_ACK::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CHAT_ACK::InternalSwap(CHAT_ACK* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, &other->_impl_.msg_, arena);
        swap(_impl_.playerid_, other->_impl_.playerid_);
}

::google::protobuf::Metadata CHAT_ACK::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[9]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
